[platformio]
src_dir = firmware/EmobotS3

[env:emobot-s3]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = firmware/partitions.csv
monitor_speed = 115200
build_flags =
    -I firmware/EmobotS3
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D WEBSOCKETS_MAX_DATA_SIZE=32768
lib_deps =
    adafruit/Adafruit SSD1306@2.5.13
    adafruit/Adafruit NeoPixel@1.12.3
    madhephaestus/ESP32Servo@1.2.1
    bblanchon/ArduinoJson@7.3.1
    links2004/WebSockets@2.6.1
    https://github.com/acrandal/RevEng_PAJ7620.git#v1.2.0
