[platformio]
src_dir = firmware/EmobotS3

[env:emobot-s3]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = firmware/partitions.csv
board_build.filesystem = fatfs
extra_scripts = pre:tools/prepare_firmware.py
monitor_speed = 115200
build_flags =
    -I firmware/EmobotS3
    -D WEBSOCKETS_MAX_DATA_SIZE=153600
lib_deps =
    adafruit/Adafruit GFX Library@1.12.6
    adafruit/Adafruit BusIO@1.17.4
    adafruit/Adafruit SSD1306@2.5.13
    adafruit/Adafruit NeoPixel@1.12.3
    madhephaestus/ESP32Servo@1.2.1
    bblanchon/ArduinoJson@7.3.1
    links2004/WebSockets@2.6.1
    https://github.com/acrandal/RevEng_PAJ7620.git#v1.2.0
